export const Types = {
    LOAD_POSTS_REQUEST: 'posts/LOAD_POSTS_REQUEST',
    DO_ERROR_REQUEST: 'posts/DO_ERROR_REQUEST',
    LOAD_POSTS_SUCCESS: 'posts/LOAD_POSTS_SUCCESS',
    LOAD_POSTS_ERROR: 'posts/LOAD_POSTS_ERROR',
    CHANGE_PAGE: 'navigation/CHANGE_PAGE',
    CHANGE_PAGE_SUCCESS: 'navigation/CHANGE_PAGE_SUCCESS',
};

